package edu.dhu.mooc.dao;

import edu.dhu.mooc.entity.Student;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    int deleteByPrimaryKey(String s_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    Student selectByPrimaryKey(String s_id);

    //自定义的DAO方法
    List<Student> selectByAccount(@Param("phone")String phone_num,@Param("password")String pwd);


    List<Student> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    int updateByPrimaryKey(Student record);


    List<Student> getStudentListByCourseId(@Param("c_id") String c_id);
}