package edu.dhu.mooc.dao;

import edu.dhu.mooc.entity.Student;
import edu.dhu.mooc.entity.Teacher;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    int deleteByPrimaryKey(String t_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    int insertSelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    Teacher selectByPrimaryKey(String t_id);

    //自定义方法
    List<Teacher> selectByAccount(@Param("phone")String phone_num, @Param("password")String pwd);
    //返回所有的老师列表
    List<Teacher> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    int updateByPrimaryKeySelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    int updateByPrimaryKey(Teacher record);
}