package edu.dhu.mooc.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table student
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Student {
    /**
     * Database Column Remarks:
     *   学生id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_id
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String s_id;

    /**
     * Database Column Remarks:
     *   真实姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_name
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String s_name;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String password;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String gender;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   学号/工号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_num
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_id
     *
     * @return the value of student.s_id
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public String getS_id() {
        return s_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_id
     *
     * @param s_id the value for student.s_id
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public void setS_id(String s_id) {
        this.s_id = s_id == null ? null : s_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_name
     *
     * @return the value of student.s_name
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    @Override
    public String toString() {
        return "Student{" +
                "s_id='" + s_id + '\'' +
                ", s_name='" + s_name + '\'' +
                ", password='" + password + '\'' +
                ", gender='" + gender + '\'' +
                ", phone='" + phone + '\'' +
                '}';
    }
}