package edu.dhu.mooc.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table student
 */
public class Student {
    /**
     * Database Column Remarks:
     *   学生id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_id
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String s_id;

    /**
     * Database Column Remarks:
     *   真实姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_name
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String s_name;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String password;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String gender;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   学号/工号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_num
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String s_num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_id
     *
     * @return the value of student.s_id
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public String getS_id() {
        return s_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_id
     *
     * @param s_id the value for student.s_id
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public void setS_id(String s_id) {
        this.s_id = s_id == null ? null : s_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_name
     *
     * @return the value of student.s_name
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public String getS_name() {
        return s_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_name
     *
     * @param s_name the value for student.s_name
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public void setS_name(String s_name) {
        this.s_name = s_name == null ? null : s_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.password
     *
     * @return the value of student.password
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.password
     *
     * @param password the value for student.password
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.phone
     *
     * @return the value of student.phone
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.phone
     *
     * @param phone the value for student.phone
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_num
     *
     * @return the value of student.s_num
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public String getS_num() {
        return s_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_num
     *
     * @param s_num the value for student.s_num
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public void setS_num(String s_num) {
        this.s_num = s_num == null ? null : s_num.trim();
    }

    @Override
    public String toString() {
        return "Student{" +
                "s_id='" + s_id + '\'' +
                ", s_name='" + s_name + '\'' +
                ", password='" + password + '\'' +
                ", gender='" + gender + '\'' +
                ", phone='" + phone + '\'' +
                ", s_num='" + s_num + '\'' +
                '}';
    }
}