package edu.dhu.mooc.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table teacher
 */
public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_id
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String t_id;

    /**
     * Database Column Remarks:
     *   真实姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_name
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String t_name;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.password
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String password;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.gender
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String gender;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.phone
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   学号/工号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_num
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    private String t_num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_id
     *
     * @return the value of teacher.t_id
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public String getT_id() {
        return t_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_id
     *
     * @param t_id the value for teacher.t_id
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public void setT_id(String t_id) {
        this.t_id = t_id == null ? null : t_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_name
     *
     * @return the value of teacher.t_name
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public String getT_name() {
        return t_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_name
     *
     * @param t_name the value for teacher.t_name
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public void setT_name(String t_name) {
        this.t_name = t_name == null ? null : t_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.password
     *
     * @return the value of teacher.password
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.password
     *
     * @param password the value for teacher.password
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.gender
     *
     * @return the value of teacher.gender
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.gender
     *
     * @param gender the value for teacher.gender
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.phone
     *
     * @return the value of teacher.phone
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.phone
     *
     * @param phone the value for teacher.phone
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_num
     *
     * @return the value of teacher.t_num
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public String getT_num() {
        return t_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_num
     *
     * @param t_num the value for teacher.t_num
     *
     * @mbg.generated Sun Mar 14 16:18:31 CST 2021
     */
    public void setT_num(String t_num) {
        this.t_num = t_num == null ? null : t_num.trim();
    }

    @Override
    public String toString() {
        return "Teacher{" +
                "t_id='" + t_id + '\'' +
                ", t_name='" + t_name + '\'' +
                ", password='" + password + '\'' +
                ", gender='" + gender + '\'' +
                ", phone='" + phone + '\'' +
                ", t_num='" + t_num + '\'' +
                '}';
    }
}